### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by 4JX** [4JX/L5P-Keyboard-RGB#124]
> I know this has been closed for over a year, but I'm currently having the same issue and I'm running into the same issue and getting the same error regardless of whether I attempt to build via cargo-make or use vcpkg then regular cargo. I doubt this is a glibc issue, at least as far as versioning, because I'm running 2.37 and it still persists

_Originally posted by @OrderlyUnicode in https://github.com/4JX/L5P-Keyboard-RGB/issues/17#issuecomment-1656563420_

@OrderlyUnicode whats the exact error?

**Comment by OrderlyUnicode** [comment]
Before I do, a bit of background. I noticed in the output I was going to place that it was complaining about not having clang, so I installed that. It technically changed the output, but the error was more or less the same, but this time, hinting at an issue with a library called yuv, which I already had installed.

<details>
<summary>Output while running cargo build --release</summary>
 Compiling scrap v0.5.0 (https://github.com/rustdesk/rustdesk?rev=6c15dd6#6c15dd6f)
error: could not find native static library `yuv`, perhaps an -L flag is missing?

error: could not compile `scrap` (lib) due to previous error
</details>

<details>
<summary>Output while running cargo make build-release</summary>
Compiling scrap v0.5.0 (https://github.com/rustdesk/rustdesk?rev=6c15dd6#6c15dd6f)
error: could not find native static library `yuv`, perhaps an -L flag is missing?

error: could not compile `scrap` (lib) due to previous error
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 5 - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
</details>

**Comment by 4JX** [comment]
Ah those look a little different, can you try in either the `Makefile.toml` for `cargo make` or in the raw procedure to change any instance of `VCPKG_INSTALLATION_ROOT` to `VCPKG_ROOT`? Assuming libvpx/libyuv where installed correctly that might be why

**Comment by OrderlyUnicode** [comment]
Editing the `Makefile.toml` had no effect. I'm unsure what you mean by changing the instances in the raw proceedure, though.

**Comment by 4JX** [comment]
If compilling it fully manually theres the step
> Download and bootstrap [VCPKG](https://github.com/Microsoft/vcpkg#getting-started)
You'll need to set an environment variable called VCPKG_INSTALLATION_ROOT pointing to the directory where you downloaded and bootstrapped VCPKG.

Where you should change the variable's name and try re-compiling the app.

Just to triple check, you *did* also run `vcpkg update && vcpkg install libvpx libyuv` once vcpkg was installed right?

**Comment by OrderlyUnicode** [comment]
Yes and no. `vcpkg update` failed with the following error

```
the update command does not currently support manifest mode. Instead, modify your vcpkg.json and run install.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

I did appear to succeed with just `vcpkg install` though

**Comment by 4JX** [comment]
> Yes and no. `vcpkg update` failed with the following error

This is expected, you only need the bootstrap step `./vcpkg/bootstrap-vcpkg.sh` and `vcpkg install...`

And then you set `VCPKG_ROOT` to the folder where you git-cloned and setup `vcpkg`

**Comment by OrderlyUnicode** [comment]
> And then you set `VCPKG_ROOT` to the folder where you git-cloned and setup `vcpkg`

I actually set it to where my package manager installed it, since I had trouble manually building vcpkg.

**Comment by OrderlyUnicode** [comment]
I did actually get it to build though by running `vcpkg install libvpx libyuv` outside the folder where I downloaded the repo.

**Comment by OrderlyUnicode** [comment]
So before this is closed, I'm going to note that I was able to reproduce the fix with a different branch of the repo by running `vcpkg install` from a different directory, editing the `Makefile.toml` file to replace `VCPKG_INSTALLATION_ROOT` with `VCPKG_ROOT`, and setting the environment variable `VCPKG_ROOT` to where my package manager installed it, which happens to be `/opt/vcpkg` but might be different for distros using different package managers, such as Ubuntu or Fedora.

**Comment by OrderlyUnicode** [comment]
Sorry, unrelated things made life a bit chaotic, so I wasn't able to say this until now. Since the fix previously mentioned has it building for me, should I close this?

**Comment by 4JX** [comment]
No need, keeping this open so that I remember to eventually update the `cargo make` file / readme build instructions 👍

**Comment by 4JX** [comment]
Closed via https://github.com/4JX/L5P-Keyboard-RGB/commit/21268d36d59c219590c1ee9002950e39a2c85115
