### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by Alireza2317** [4JX/L5P-Keyboard-RGB#149]
Hello there.
I have a simple issue with the `settings.json` file. currently the app auto-creates it in my home direcory `~`, but i would like to change its directory to somewhere else. how can i do that?
i think there should be a option in the gui to set this easily.

**Comment by 4JX** [comment]
I cannot do this from the GUI since the program would need to still need to have some known place to look up the fact it has to read the config from somewhere else. 

A few options come to mind to specify a place to read/write to:
- A CLI flag 
- An environment variable
- Just dropping it in `$XDG_CONFIG_HOME`/`$HOME/.config` but that feels less flexible and explicit than the other two

**Comment by Alireza2317** [comment]
I think an _environment variable_ is ok. but there is no solution for this right now?

**Comment by 4JX** [comment]
Not at the moment

**Comment by 4JX** [comment]
Apologies for the delay, can you test if https://github.com/4JX/L5P-Keyboard-RGB/actions/runs/8667189970 does the job for you?

**Comment by Alireza2317** [comment]
i'm sorry but what is the difference of this version exactly? i can't feel anything different. do i have to set an enviornment variable for the `settings.json` path?

**Comment by 4JX** [comment]
Whoops, my brain went into autopilot mode since I added an explanation to the readme in the same commit 😅. 

Yes, try setting `LEGION_KEYBOARD_CONFIG` to point to a config file elsewhere.

**Comment by Alireza2317** [comment]
well it worked quite nicely! thank you.

**Comment by 4JX** [comment]
Closed via https://github.com/4JX/L5P-Keyboard-RGB/releases/tag/v0.19.6
