### ISSUE TITLE
Win11 compatibility

### ISSUE THREAD

**Issue by TheMjW** [4JX/L5P-Keyboard-RGB#29]
Does not start in Win11 at all. Crashes at launch.
Don't know if there is something more I need to install?

**Comment by 4JX** [comment]
Are you able to control the lights through Vantage?

**Comment by TheMjW** [comment]
I can cycle through the available profiles and turn off RGB with the keyboard shortcut (FN+Space), but when I click to edit said profiles in Vantage I get a message that a driver installation is needed to activate RGB, and an Install button appears.

Clicking the install button goes to Vantage's driver search which comes up empty. I tried reinstalling vantage but it's always the same results.

**Comment by 4JX** [comment]
> Clicking the install button goes to Vantage's driver search which comes up empty. I tried reinstalling vantage but it's always the same results.

Does it cycle through 3 or 4 modes (+ off)? If its 4 then its using the ones built into the hardware and not being detected or controlled by Vantage in any way, which would be a similar case to https://github.com/4JX/L5P-Keyboard-RGB/issues/23#issuecomment-965750477 and therefore not something I can fix. (Since nothing can "talk" to the keyboard)

**Comment by TheMjW** [comment]
Ah yes, it cycles 4 modes. Hopefully it's a driver issue that might be fixed by Lenovo and not a H/W issue. Can't wait to try your software if this is ever rectified.

Thank you for the fast replies!

**Comment by 4JX** [comment]
Lenovo drivers bug - Outside of what I can fix.

Related: https://github.com/4JX/L5P-Keyboard-RGB/issues/23#issuecomment-965750477
