### ISSUE TITLE
After first time usage, the layout is locked on Win11

### ISSUE THREAD

**Issue by aarmn** [4JX/L5P-Keyboard-RGB#37]
basically the thunder mode doesnt turn off and I cant change to others not from kb shortuct nor app or app cli

**Comment by 4JX** [comment]
(Assuming that by thunder you mean the "Lightning" effect)

On Windows the default behavior is to close *to tray* (which I should probably be more explicit about). You'll see there's also an "exit" button for fully terminating the process. Otherwise you can always access the tray and close it from there.
