### ISSUE TITLE
Make a library

### ISSUE THREAD

**Issue by heckert-gamedev** [4JX/L5P-Keyboard-RGB#43]
It would be really nice if there was a library for this one could use in one's own projects without the performance hit of running a separate program for each effect.
(My intended target platform would be Unity on Linux and Windows)

**Comment by 4JX** [comment]
https://github.com/4JX/L5P-Keyboard-RGB/blob/main/src/keyboard_utils.rs

Is actually all you really need to get started, I'll see about uploading it to crates.io as a standalone thing. Really curious about what it could be used for 😁

**Comment by 4JX** [comment]
Hmm, I'm having trouble with coming up with a meaningful enough name for the library. Any ideas?

**Comment by heckert-gamedev** [comment]
As for the Rust vs. C# issue, I actually came across this one the other day:
"Rust and Unity game development" https://youtu.be/L7M_vbo1N2g
>  I added Rust support for the Unity game engine.
Is it really possible? YES it is!
I managed to make a game 100% coded in Rust, but using Unity as editor and runtime.
This has to be one of my craziest projects yet!
> 
> I utilized a library called Bevy game framework/engine, to handle the gameplay programming. Utilizing Bevy systems I was able to hide the Foreign Function interfacing code from the gameplay code.
> 
> Runity Source code:
https://github.com/TanTanDev/runity

It sounds like this would be a good starting point, at least... (I haven't looked into it yet, it's just something I came across and found interesting enough to bookmark, probably because the idea for this suggestion was already brewing somewhere in my head)

As for a name... Maybe it's the Rusty Blinken-Keyboard? The Legionary Keyboard-Blinker? Disco-Keys for Unity?

**Comment by 4JX** [comment]
I've been fiddling around with this for a while now but I cannot wrap my head around implementing this with my current (lacking) knowledge of the language (It gets especially finicky when having to handle the `AtomicBool` stop signal and whatnot). 

You can try your luck with it:
- Separate repo with only the core library: https://github.com/4JX/lenovo-legion-hid
- Relevant discussion in the Rust forums: https://users.rust-lang.org/t/first-time-trying-to-do-ffi-bindings/69054

**Comment by heckert-gamedev** [comment]
Since I don't have any knowledge of Rust (nor the underlying system level APIs) all I can give are just suggestions...

**Comment by 4JX** [comment]
I may revisit this at a latter date, but for now I'd rather keep improving my level in the language.

You could also try translating the code to native C#, its mostly a matter of seeing if there's a `hidapi` library available in that language.

**Comment by fu-raz** [comment]
I know it has been a while since this was brought up, but I'm actually in the process of trying to get this to work in C#. I've built a Razer Connected device app and I'm trying to light up the keyboard using Razer software. I've been digging into your code and it seems pretty straight forward. I just can't get it to work.

I'm using this HID API Adapter (https://github.com/nvchernov/hidapiadapter) and I can find the device. Then I build a byte array following your build_payload function and write it to the device. But then when I run the code and nothing happens. I'm trying to send the following as a p.o.c.
`byte[] testColor = new byte[32] {
                0xcc,
                0x16,
                0x01,
                1,
                2,
                255,
                0,
                0,
                0,
                255,
                0,
                0,
                0,
                255,
                255,
                0,
                255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
            };`

The API Adapter automatically adds the leading 0 etc, so that should be fine. Am I doing something wrong here? Or is it something else?
